### ISSUE TITLE
Remove dead provider

### ISSUE THREAD

**Issue by antikirra** [1ort/checkr#1]
https://github.com/1ort/checkr/blob/6bc6cce91cb410ab7e79b2b50266443b2886b96a/cmd/main.go#L19

**Comment by antikirra** [comment]
Last commit - 2022-09-05T07:00:23Z
https://api.github.com/repos/clarketm/proxy-list/commits?page=1&per_page=1

**Comment by 1ort** [comment]
Hello. If this source has not been updated for a long time, this does not mean that all the proxies in it are dead. You can check this list separately and see for yourself.
`checkr -url https://raw.githubusercontent.com/clarketm/proxy-list/master/proxy-list-raw.txt`
At the time of my post there were at least 30 live proxies.

On the other hand, it is better to make sure that these proxies do not come across to us in other lists. If so, then we can safely remove this provider from the checker without
